fmt:
	ruff check --select I --fix .
	ruff format . --no-cache
	@echo '[OK] Formatters went through successfully'

lint:
	ruff check solution --no-cache
	@echo '[OK] Linters checks passed successfully'
